### PR TITLE
Several small fixes and improvements

### PR DESCRIPTION
**Pull request by berendkleinhaneveld**
Thanks for making this tool! Comes in really handy!
While using it, I stumbled on some small issues, so here is a pull request which should fix those.

* Replaced a deprecated Qt method with a newer
* Added shortcuts for 
    * opening image folder (Ctrl+O)
    * opening configuration file (Ctrl+Shift+O)
* Fixed shortcuts for labels not working after loading other configuration file
* Changed the shortcuts of labels to be even easier (less modifier keys)
* Refactor whitespace and coding style here and there (sorry, can't help it while I'm reading code ;) )

### CODE REVIEW

**Comment by berendkleinhaneveld** [comment]
I'm currently fixing the Appveyor CI. Seems that the latest version of `curl` is a bit too sensitive (https://github.com/curl/curl/issues/4624). For now I'm trying out an earlier version.

**Comment by berendkleinhaneveld** [comment]
CI is passing again!

**Comment by abreheret** [comment]
Thank you for your contribution, I will release if you have no other features to add ?

**Comment by berendkleinhaneveld** [comment]
There are two things that I would like to add in another PR: 'Save all masks' and keyboard shortcuts to select the next/previous file in the folder, but don't let me stop you from releasing another version. I'm ok either way!

**Pull request merged**
